/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface OoyalaPlayerComponent {
    'first': string;
    'last': string;
  }
  interface OoyalaPlayerComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'OoyalaPlayerComponent': Components.OoyalaPlayerComponent;
  }

  interface StencilIntrinsicElements {
    'ooyala-player-component': Components.OoyalaPlayerComponentAttributes;
  }


  interface HTMLOoyalaPlayerComponentElement extends Components.OoyalaPlayerComponent, HTMLStencilElement {}
  var HTMLOoyalaPlayerComponentElement: {
    prototype: HTMLOoyalaPlayerComponentElement;
    new (): HTMLOoyalaPlayerComponentElement;
  };

  interface HTMLElementTagNameMap {
    'ooyala-player-component': HTMLOoyalaPlayerComponentElement
  }

  interface ElementTagNameMap {
    'ooyala-player-component': HTMLOoyalaPlayerComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
